### ISSUE TITLE
Newlines overwrite link text when inserting a link

### ISSUE THREAD

**Issue by dnsl48** [springload/wagtaildraftail#20]
How to reproduce:

1. write a sentence
2. press `Shift+Alt+Left`
3. press `Link` button
4. choose a link
5. see that the text is not highlighted anymore
6. press `Enter`
7. `newline` symbol overwrote the link sentence

**Comment by thibaudcolas** [comment]
Moving this to https://github.com/springload/draftail/issues/108 as the issue is not specific to the editor being within Wagtail.
