### ISSUE TITLE
Change block/field default to None

### ISSUE THREAD

**Issue by loicteixeira** [springload/wagtaildraftail#32]
Currently, the default value is an empty dict which is basically an invalid content state. Therefore, the editor should return `None` which clearly state the lack of content.

- [x] Update [springload/draftail](https://github.com/springload/draftail/issues/56) package.
- [x] Update [springload/draftjs_exporter](https://github.com/springload/draftjs_exporter/issues/60) package.
- [x] Update `springload/draftail` dependency for this package.
- [x] Update `springload/draftjs_exporter` dependency for this package.
- [ ] Update block accordingly
- [ ] Update field accordingly (actually the field doesn't have a default value atm?)
- [ ] Remove the now useless [form field](https://github.com/springload/wagtaildraftail/blob/ade5cd35486c156adebc62423dca7a102b8ca47c/wagtaildraftail/forms.py) and [validator](https://github.com/springload/wagtaildraftail/blob/ade5cd35486c156adebc62423dca7a102b8ca47c/wagtaildraftail/validators.py)?

**Comment by thibaudcolas** [comment]
@loicteixeira I've done the work in Draftail (#40) and the exporter (#36) to support this, and updated those two here – will leave the Django changes to you if you have the time.

**Comment by thibaudcolas** [comment]
I have re-added a default value of `{}` within this project (https://github.com/springload/wagtaildraftail/pull/42/commits/bb4b68ff9cd9c88985e58070b59184985afabe80) so that we can finish this later on.

Note that nothing needs to happen for the exporter, it will handle `None` or `{}` just the same.

**Comment by loicteixeira** [comment]
Sorry I didn't get time to look into this before my break.

Basically, the block use a [custom form field](https://github.com/springload/wagtaildraftail/blob/378024960faae49cf552c4a69b9cad2541005bcc/wagtaildraftail/blocks.py#L28) to handle the `'{}'` string as empty.

Now that `draftail` returns `None`, this is not needed anymore. This can probably use the same `formfield` as the parent class, so there is no need for the form and validator linked above in the issue.

FWIW, it looks like `DraftailTextBlock` and `DraftailTextField` don't use the same underlying form field and this should be updated to the same (but potentially removing the overwrite on the block should do the trick).
