### ISSUE TITLE
No Static Assets being compiled / static directory present for deploying

### ISSUE THREAD

**Issue by tacitus** [springload/wagtaildraftail#54]
This causes collectstatic to miss the required js and css  since it cannot find the static dir for the app, and the assets don't get deployed.

Required for rolling out via a package manager.

**Comment by thibaudcolas** [comment]
As far as I can see the compiled assets are where they are expected to be (see screenshot from pypi package below).

<img width="994" alt="screen shot 2017-06-01 at 10 23 38" src="https://cloud.githubusercontent.com/assets/877585/26671060/7520bd14-46b4-11e7-9742-c1b985c5c73f.png">

The most likely issue is that you are installing from the GitHub repo, which is not supported:

```txt
# requirements.txt
git+git://github.com/springload/wagtaildraftail.git@fix/51
```
